services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-controller
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  jenkins-agent:
    build:
      context: ./jenkins-agent
    container_name: jenkins-agent
    restart: unless-stopped
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${JENKINS_AGENT_SSH_PUBKEY:-}"
      DOCKER_HOST: "tcp://jenkins-docker:2375"
      DOCKER_TLS_CERTDIR: ""
      KUBECONFIG: "/home/jenkins/.kube/config"
    depends_on:
      - docker
    volumes:
      - "C:/scripts/projects/project2/jenkins-kube:/home/jenkins/.kube:ro"
    networks:
      - jenkins-net

  docker:
    image: docker:27-dind
    container_name: jenkins-docker
    restart: unless-stopped
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
      - --insecure-registry=nexus:5000
    volumes:
      - docker_data:/var/lib/docker
    networks:
      - jenkins-net
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jenkins-net

volumes:
  jenkins_home:
  nexus-data:
  docker_repository_data:
  docker_data:
  devops_helper_data:

networks:
  jenkins-net:
    driver: bridge
