apiVersion: v1
kind: Namespace 
metadata:
  name: test-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
spec:
  selector:
    matchLabels:
      app: test-image
  template:
    metadata:
      labels:
        app: test-image
    spec:
      containers:
      - name: test-image
        image: nexus:5000/my-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-image
  ports:
  - port: 3000
    nodePort: 30080
    targetPort: 5000
